[tool.poetry]
name = "netdev"
version = "0.9.1"
description = "Asynchronous multi-vendor library for interacting with network devices"
authors = ["Sergey Yakovlev <selfuryon@gmail.com>"]
license = "Apache-2.0"
readme = "README.rst"
repository = "https://github.com/selfuryon/netdev"
classifiers = [
        # 3 - Alpha
        # 4 - Beta
        # 5 - Production/Stable
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Intended Audience :: System Administrators",
        "Topic :: System :: Networking",
]

[tool.poetry.dependencies]
python = ">=3.6"
PyYAML = "^5.1"
asyncssh = "^1.15"

[tool.poetry.dev-dependencies]
PyYAML = ">=5.1"
asyncssh = ">=1.15"
black = {version = "^19.3b0",allows-prereleases = true}
sphinx = "^2"
sphinx_rtd_theme = "^0.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
