---
name: Testing workflow

on: [push]

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache poetry
      uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Unittests
      run: |
        poetry run pytest tests/unit/ --cov=netdev

