---
name: Testing workflow

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry
        poetry install
    - name: Test with pytest
      run: |
        pytest tests/ --cov=netdev

