---
name: Testing workflow

on: [push]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Cache poetry
      uses: actions/cache@v1
      with:
        path: ~/.config/pypoetry
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-poetry-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
          ${{ runner.os }}-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry config --list
        poetry install
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests/ --cov=netdev

